run_name: intro-notebook
notes: null

data:
  dataset_name: cora
  dataset_path: /content/drive/MyDrive/neuralcora/data/NY_2013_180_360_demo.nc
  mask_path: /content/drive/MyDrive/neuralcora/data/real_land_mask_180_360.nc
  input_steps: 1
  forecast_steps: 6
  stride: 1
  normalization: global
  stats_path: null
  batch_size: 2
  num_workers: 0
  split_fractions:
    train: 0.8
    val: 0.1
    test: 0.1

model:
  name: simple_cnn
  # To do: resnet, unet, vit
  input_channels: 1
  output_channels: 6
  hidden_channels:
    - 32
    - 64
  kernel_size: 3
  dropout: 0.1

training:
  trainer_name: basic
  epochs: 2
  learning_rate: 0.1
  weight_decay: 0.0
  device: auto
  log_interval: 25
  save_dir: runs
  gradient_clip_norm: null

# To do: evaluation: